CREATE TABLE `company` (
  `company_id` char(21) NOT NULL,
  `company_name` varchar(200) NOT NULL,
  `company_email` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `industry` text NOT NULL,
  `city_municipality` varchar(100) NOT NULL,
  `barangay` varchar(100) NOT NULL,
  `telephone_number` varchar(20) DEFAULT NULL,
  `phone_number` varchar(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `facebook_page` varchar(255) DEFAULT NULL,
  `instagram_page` varchar(255) DEFAULT NULL,
  `twitter_page` varchar(255) DEFAULT NULL,
  `date_founded` date NOT NULL,
  `mou_path` varchar(255) DEFAULT NULL,
  `loi_path` varchar(255) DEFAULT NULL,
  `cp_path` varchar(255) DEFAULT NULL,
  `business_permit_path` varchar(255) DEFAULT NULL,
  `mayor_permit_path` varchar(255) DEFAULT NULL,
  `dti_permit_path` varchar(255) DEFAULT NULL,
  `bir_cert_of_registration_path` varchar(255) DEFAULT NULL,
  `company_image` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_c