CREATE TABLE `job_posts` (
  `job_post_id` char(21) NOT NULL,
  `company_id` char(21) NOT NULL,
  `job_post_status_id` int(11) NOT NULL,
  `job_title` varchar(255) NOT NULL,
  `work_arrangement` enum('On-site','Hybrid','Remote') NOT NULL,
  `job_categories` varchar(100) DEFAULT NULL,
  `job_overview` text NOT NULL,
  `available_positions` smallint(6) NOT NULL,
  `courses_required` text NOT NULL,
  `job_responsibilities` text NOT NULL,
  `technical_skills` text NOT NULL,
  `soft_skills` text DEFAULT NULL,
  `preferred_qualifications` text DEFAULT NULL,
  `is_paid` tinyint(1) DEFAULT 0,
  `allowance_description` varchar(255) DEFAULT NULL,
  `street_name` varchar(100) NOT NULL,
  `city_municipality` varchar(255) NOT NULL,
  `barangay` varchar(255) NOT NULL,
  `postal_code` char(4) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`job_post_id`),
  KEY `COMPANY_ID_JOB_POSTS_FK` (`company_id`),
  KEY `STATUS_ID_JOB_POSTS_FK` (`job_post_status_id`),
  CONSTRAINT `COMPANY_ID_JOB_POSTS_FK` FOREIGN KEY (`company_id`) REFERENCES `company` (`company_id`) ON DELETE CASCADE,
  CONSTRAINT `STATUS_ID_JOB_POSTS_FK` FOREIGN KEY (`job_post_status_id`) REFERENCES `status` (`status_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci